# @package _global_

defaults:
  - /algo/sac/module: large
  - override /algo: mimic_lite_sac

total_iters: 5000
checkpoint_interval: 1000
upload_interval: 1000

algo:
  gamma: 0.95
  buffer_size: 256
  buffer_device: "cuda"
  use_correlated: false
  actor_loc_reg_scale: 16.0
  actor_loc_reg_power: 4.0
  critic_batch_size: 4096
  actor_batch_size: 4096

task:
  num_envs: 8192
