# @package task
defaults:
  - command/future_steps: short
  - observation/priv: root_body_actions
  - observation/command: joint
  - observation/command_short: joint
  - termination: base
  - motion: mini3/sonic
  - _self_

name: Mini3TrackBase
project: mimic_lite

shared:
  root_body_name: base_link
  anchor_body_name: base_link
  reward_root_body_name: waist_yaw_link
  termination_root_body_name: base_link
  obs_body_names:
    - "base_link"
    - "waist_yaw_link"
    - ".*_knee_pitch_link"
    - ".*_ankle_roll_link"
    - ".*_shoulder_yaw_link"
    - ".*_elbow_pitch_link"

  tracking_body_names:
    - "base_link"
    - "waist_yaw_link"
    - ".*_hip_yaw_link"
    - ".*_knee_pitch_link"
    - ".*_ankle_roll_link"
    - ".*_shoulder_yaw_link"
    - ".*_elbow_pitch_link"
  tracking_joint_names:
    - left_hip_pitch_joint
    - left_hip_roll_joint
    - left_hip_yaw_joint
    - left_knee_pitch_joint
    - left_ankle_pitch_joint
    - left_ankle_roll_joint
    - right_hip_pitch_joint
    - right_hip_roll_joint
    - right_hip_yaw_joint
    - right_knee_pitch_joint
    - right_ankle_pitch_joint
    - right_ankle_roll_joint
    - waist_yaw_joint
    - left_shoulder_pitch_joint
    - left_shoulder_roll_joint
    - left_shoulder_yaw_joint
    - left_elbow_pitch_joint
    - right_shoulder_pitch_joint
    - right_shoulder_roll_joint
    - right_shoulder_yaw_joint
    - right_elbow_pitch_joint
  reward_joint_names:
    - ".*_hip_.*_joint"
    - ".*_knee_pitch_joint"
    - ".*_ankle_.*_joint"
    - "waist_yaw_joint"
    - ".*_shoulder_.*_joint"
    - ".*_elbow_pitch_joint"

viewer:
  resolution: [1280, 720]
  lookat: [0.0, 0.0, 0.0]
  eye: [4.0, 4.0, 4.0]

terrain: plane
enable_cameras: false

num_envs: 8192
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

robot:
  name: mini3-mesh

input:
  action:
    _target_: mimic_lite.JointPosition
    action_scaling:
      left_hip_pitch_joint: 0.25
      left_hip_roll_joint: 0.25
      left_hip_yaw_joint: 0.25
      left_knee_pitch_joint: 0.25
      left_ankle_pitch_joint: 0.25
      left_ankle_roll_joint: 0.25
      right_hip_pitch_joint: 0.25
      right_hip_roll_joint: 0.25
      right_hip_yaw_joint: 0.25
      right_knee_pitch_joint: 0.25
      right_ankle_pitch_joint: 0.25
      right_ankle_roll_joint: 0.25
      waist_yaw_joint: 0.25
      left_shoulder_pitch_joint: 0.25
      left_shoulder_roll_joint: 0.25
      left_shoulder_yaw_joint: 0.25
      left_elbow_pitch_joint: 0.25
      right_shoulder_pitch_joint: 0.25
      right_shoulder_roll_joint: 0.25
      right_shoulder_yaw_joint: 0.25
      right_elbow_pitch_joint: 0.25
    min_delay: 1
    max_delay: 3
    alpha_range: [0.8, 1.0]

command:
  _target_: mimic_lite.RobotTracking
  motion_cfgs: ???
  tracking_body_names: ${task.shared.tracking_body_names}
  obs_body_names: ${task.shared.obs_body_names}
  tracking_joint_names: ${task.shared.tracking_joint_names}
  diff_future_steps: [0, 1]
  root_body_name: ${task.shared.root_body_name}
  anchor_body_name: ${task.shared.anchor_body_name}
  windowed_next_window_device: cpu
  windowed_pin_window_load: true

  # TODO: put this into randomization reset callbacks
  pose_range:
    x: [-0.05, 0.05]
    y: [-0.05, 0.05]
    z: [-0.01, 0.01]
    roll: [-0.1, 0.1]
    pitch: [-0.1, 0.1]
    yaw: [-0.1, 0.1]
  velocity_range:
    x: [-0.2, 0.2]
    y: [-0.2, 0.2]
    z: [-0.2, 0.2]
    roll: [-0.5, 0.5]
    pitch: [-0.5, 0.5]
    yaw: [-0.5, 0.5]

  init_joint_pos_noise: 0.1
  init_joint_vel_noise: 0.1

  rewind_prob: 0.8
  rewind_steps_range: [25, 125]

observation:
  command:
    ref_root_lin_vel_future_local:
      _target_: mimic_lite.ref_root_lin_vel_future_local
  command_short:
    ref_root_lin_vel_future_local:
      _target_: mimic_lite.ref_root_lin_vel_future_local
  policy:
    root_ang_vel_history:
      _target_: mimic_lite.root_ang_vel_history
      history_steps: [0, 1, 2, 3, 4, 8, 16]
      noise_std: 0.2
    projected_gravity_history:
      _target_: mimic_lite.projected_gravity_history
      history_steps: [0, 1, 2, 3, 4, 8, 16]
      noise_std: 0.01
    joint_pos_history:
      _target_: mimic_lite.joint_pos_history
      history_steps: [0, 1, 2, 3, 4, 8, 16]
      noise_std: 0.02
    joint_vel_history:
      _target_: mimic_lite.joint_vel_history
      history_steps: [0, 1, 2, 3, 4, 8, 16]
      noise_std: 0.5
    prev_actions:
      _target_: mimic_lite.prev_actions
      steps: 3
  ref_joint_pos_:
    ref_joint_action:
      _target_: mimic_lite.ref_joint_action
  _motion_length:
    motion_length:
      _target_: mimic_lite.motion_length

reward:
  tracking:
    root_pos:
      _target_: mimic_lite.body_pos_exp
      body_names: ["${task.shared.reward_root_body_name}"]
      enabled: true
      weight: 0.5
      sigma: 0.2
    root_ori:
      _target_: mimic_lite.body_ori_exp
      body_names: ["${task.shared.reward_root_body_name}"]
      weight: 0.5
      sigma: 0.4
    root_linvel:
      _target_: mimic_lite.body_lin_vel_exp
      body_names: ["${task.shared.reward_root_body_name}"]
      weight: 0.5
      sigma: 1.0
    root_angvel:
      _target_: mimic_lite.body_ang_vel_exp
      body_names: ["${task.shared.reward_root_body_name}"]
      weight: 0.5
      sigma: 2.5

    body_pos:
      _target_: mimic_lite.body_pos_local_exp
      body_names: ${task.shared.tracking_body_names}
      weight: 1.0
      sigma: 0.2
    body_ori:
      _target_: mimic_lite.body_ori_local_exp
      body_names: ${task.shared.tracking_body_names}
      weight: 1.0
      sigma: 0.4

    body_linvel:
      _target_: mimic_lite.body_lin_vel_exp
      body_names: ${task.shared.tracking_body_names}
      weight: 0.5
      sigma: 1.0
    body_angvel:
      _target_: mimic_lite.body_ang_vel_exp
      body_names: ${task.shared.tracking_body_names}
      weight: 0.5
      sigma: 2.5


    joint_pos:
      _target_: mimic_lite.joint_pos_tracking_product
      joint_names: ${task.shared.reward_joint_names}
      weight: 0.5
      sigma: 0.25
    joint_vel:
      _target_: mimic_lite.joint_vel_tracking_product
      joint_names: ${task.shared.reward_joint_names}
      weight: 0.5
      sigma: 2.5

  loco:
    action_rate_l2:     {weight: 0.1, enabled: true}
    joint_vel_l2:       {weight: 1.0e-4, joint_names: .*}
    joint_pos_limits:
      _target_: mimic_lite.joint_pos_limits
      weight: 10.0
      joint_names: ".*"
      soft_factor: 0.9
      enabled: true
    self_collisions:
      _target_: mimic_lite.self_collisions
      weight: -1.0
      enabled: true
      sensor_name: self_collision
      force_threshold: 1.0

    feet_slip:
      _target_: mimic_lite.feet_slip
      weight: 0.5
      tolerance: 0.0
      enabled: true
      body_names: .*ankle_roll_link

    feet_air_time:
      _target_: mimic_lite.feet_air_time
      weight: 4.0
      enabled: true
      body_names: [left_ankle_roll_link, right_ankle_roll_link]
      thres: 0.8
      height_range: [0.03, 0.10]
      time_factor_range: [0.2, 1.0]

    survival:           {weight: 4.0, enabled: true}
  tracking_metrics:
    _enabled_: false
    root_pos:
      _target_: mimic_lite.body_pos_error
      body_names: ["${task.shared.reward_root_body_name}"]
      weight: 1.0
      enabled: false
    root_ori:
      _target_: mimic_lite.body_ori_error
      body_names: ["${task.shared.reward_root_body_name}"]
      weight: 1.0
      enabled: false
    body_pos:
      _target_: mimic_lite.body_pos_error_local
      body_names: ${task.shared.tracking_body_names}
      weight: 1.0
      enabled: false
    body_ori:
      _target_: mimic_lite.body_ori_error_local
      body_names: ${task.shared.tracking_body_names}
      weight: 1.0
      enabled: false
    joint_pos:
      _target_: mimic_lite.joint_pos_error
      joint_names: ${task.shared.reward_joint_names}
      weight: 1.0
      enabled: false
  loco_metrics:
    _enabled_: false
    joint_pos_limits:
      _target_: mimic_lite.joint_pos_limits
      weight: 1.0
      joint_names: ".*"
      soft_factor: 0.9
      enabled: false

    feet_contact_count:
      _target_: mimic_lite.feet_contact_count
      weight: 1.0
      enabled: false
      body_names: .*ankle_roll_link

    feet_contact_duration:
      _target_: mimic_lite.feet_contact_duration
      weight: 1.0
      enabled: false
      body_names: .*ankle_roll_link

randomization:
  # startup
  perturb_body_materials:
    body_names: [".*ankle_roll_link", ".*_elbow_pitch_link"]
    static_friction_range: [0.3, 1.6]
    dynamic_friction_range: [0.3, 1.2]
    restitution_range: [0.0, 0.5]
    solref_time_constant_range: [0.015, 0.03]
    solref_dampratio_range: [0.5, 2.0]
    homogeneous: true

  perturb_body_mass:
    base_link: [0.9, 1.1]
    waist_yaw_link: [0.9, 1.1]
  perturb_body_com:
    "base_link|waist_yaw_link": [-0.03, 0.03]

  motor_params_implicit:
    stiffness_range:
      ".*(shoulder|elbow).*": [0.9, 1.1]
      ".*(waist|hip|knee|ankle).*": [0.8, 1.2]
    damping_range:
      ".*(shoulder|elbow).*": [0.9, 1.1]
      ".*(waist|hip|knee|ankle).*": [0.8, 1.2]
    armature_range:
      .*: [0.75, 1.25]
    friction_range:
      ".*(hip|knee|waist).*": [0.736617, 1.368004]
      ".*ankle.*": [0.35, 1.40]
      ".*(shoulder|elbow).*": [0.49, 0.91]


  # reset
  random_joint_offset:
    .*: [-0.01, 0.01]

  # interval
  perturb_root_vel:
    min_s: 4.0
    max_s: 6.0

    x: [-0.2, 0.2]
    y: [-0.2, 0.2]
    z: [-0.1, 0.1]
    roll: [-0.2, 0.2]
    pitch: [-0.2, 0.2]
    yaw: [-0.4, 0.4]
