# @package _global_

defaults:
  - override /algo: ppo_roa_train

total_iters: 4000
checkpoint_interval: 1000
upload_interval: 1000

algo:
  freeze_vecnorm: false
  entropy_coef_start: 0.012
  entropy_coef_end: 0.002
  entropy_decay_start: 2000
  entropy_decay_end: 3000
