# @package _global_

stages:
  - name: train
    overrides:
      - +exp=ppo_roa/train
    load_checkpoint_from_previous: false
  - name: adapt
    overrides:
      - +exp=ppo_roa/adapt
    load_checkpoint_from_previous: true
  - name: finetune
    overrides:
      - +exp=ppo_roa/finetune
    load_checkpoint_from_previous: true
